"""CompetitorStoreAgent — opposing dark store with its own LLM (or scripted policy).

In MarketCommonsEnv, this agent runs a separate FreshPriceEnv-shaped
inventory and competes with the hero StoreAgent for:

  - Customer attention (consumers compare prices across stores)
  - Farmer surplus (a farmer broadcasts to all stores; whoever bids
    fastest at a viable price wins)
  - Trend supply (only one store can lock down the limited supply of
    a viral category)

Personas determine the policy:

  AGGRESSIVE   — undercuts the hero by 5-10% on overlapping SKUs,
                 races to grab any viable farmer offer
  COOPERATIVE  — willing to forward farmer offers, accepts mutual
                 transfers, occasional pareto-improving COMMITs
  RECIPROCAL  — mirrors the hero's last 3 actions
  RANDOM      — uniform over options (baseline for ablations)

When ``llm_client`` is provided, the agent's outgoing messages are
generated by the LLM. Otherwise the scripted policy emits the same
verbs deterministically.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from enum import Enum

from freshprice_env.entities import SimulatedFarmerOffer, SimulatedMarketState
from freshprice_env.protocol.market_bus import MarketBus, MessageVerb


class CompetitorPersona(str, Enum):
    AGGRESSIVE = "AGGRESSIVE"
    COOPERATIVE = "COOPERATIVE"
    RECIPROCAL = "RECIPROCAL"
    RANDOM = "RANDOM"


@dataclass
class CompetitorAction:
    """One competitor action — the env applies this to the shared market."""

    kind: str                    # "PRICE_MOVE" | "OFFER_BID" | "TREND_GRAB" | "TRANSFER" | "MESSAGE"
    target_id: str | None
    payload: dict = field(default_factory=dict)
    body: str = ""


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

class CompetitorStoreAgent:
    """A second store with its own state and an opposing policy.

    The MarketCommonsEnv calls ``observe(state, hero_state)`` to give
    the agent a partial view, then ``act(...)`` to get a list of
    CompetitorAction. Every produced action is also logged to the bus.
    """

    def __init__(
        self,
        store_id: str,
        persona: CompetitorPersona,
        rng: random.Random,
        bus: MarketBus | None = None,
        llm_client=None,
        undercut_pct: float = 0.07,
    ) -> None:
        self.store_id = store_id
        self.persona = persona
        self._rng = rng
        self._bus = bus
        self._llm = llm_client
        self._undercut_pct = float(undercut_pct)

        # Internal state
        self._cash: float = 5000.0
        self._inventory_at_risk_units: int = 0
        self._hero_action_history: list[str] = []   # last K hero kinds for RECIPROCAL

    # ------------------------------------------------------------------
    # Observation
    # ------------------------------------------------------------------

    def observe(
        self,
        own_state: SimulatedMarketState | None,
        hero_state: SimulatedMarketState,
        last_hero_action_kind: str | None = None,
    ) -> dict:
        """Build a structured observation."""
        if last_hero_action_kind:
            self._hero_action_history.append(last_hero_action_kind)
            if len(self._hero_action_history) > 6:
                self._hero_action_history.pop(0)
        critical = sum(
            1 for b in hero_state.batches if b.is_at_risk
        )
        pending = len(hero_state.pending_offers)
        return {
            "hero_critical_batches": critical,
            "hero_pending_offers": pending,
            "hero_wrr": round(hero_state.wrr, 3),
            "own_cash": round(self._cash, 2),
            "persona": self.persona.value,
            "recent_hero_kinds": list(self._hero_action_history),
        }

    # ------------------------------------------------------------------
    # Decision-making
    # ------------------------------------------------------------------

    def act(
        self,
        own_state: SimulatedMarketState | None,
        hero_state: SimulatedMarketState,
        farmer_offers_in_pool: list[SimulatedFarmerOffer],
        active_trend_categories: list[str],
        current_tick: int,
    ) -> list[CompetitorAction]:
        """Return the actions this competitor takes this brief cycle."""
        actions: list[CompetitorAction] = []

        # --- 1. Price-move on overlapping SKUs -----------------------
        actions.extend(self._price_move_actions(hero_state, current_tick))

        # --- 2. Bid on farmer offers ---------------------------------
        actions.extend(
            self._farmer_bid_actions(farmer_offers_in_pool, current_tick)
        )

        # --- 3. Try to lock down trend supply ------------------------
        actions.extend(
            self._trend_grab_actions(active_trend_categories, current_tick)
        )

        # --- 4. Optionally send cooperative MESSAGE ------------------
        actions.extend(self._message_actions(current_tick))

        # Post all actions to bus
        if self._bus is not None:
            for a in actions:
                self._bus.post(
                    tick=current_tick,
                    sender_id=self.store_id,
                    verb=_action_to_verb(a),
                    body=a.body or f"{a.kind} {a.target_id or ''}".strip(),
                    receiver_id=a.payload.get("receiver_id"),
                    payload={"kind": a.kind, **a.payload},
                )

        return actions

    # ------------------------------------------------------------------
    # Persona policies
    # ------------------------------------------------------------------

    def _price_move_actions(
        self, hero_state: SimulatedMarketState, current_tick: int,
    ) -> list[CompetitorAction]:
        """Persona-specific price moves on the hero's at-risk batches."""
        out: list[CompetitorAction] = []
        if self.persona == CompetitorPersona.RANDOM:
            return out
        # Find at-risk hero batches
        at_risk = [b for b in hero_state.batches if b.is_at_risk]
        if not at_risk:
            return out
        target = self._rng.choice(at_risk)

        if self.persona == CompetitorPersona.AGGRESSIVE:
            multiplier = max(0.45, 1.0 - self._undercut_pct - self._rng.uniform(0.02, 0.08))
            out.append(CompetitorAction(
                kind="PRICE_MOVE",
                target_id=target.batch_id,
                payload={
                    "category": target.category,
                    "price_multiplier": round(multiplier, 3),
                    "reason": "undercut hero",
                },
                body=(
                    f"{self.store_id}: matching {target.category} clearance "
                    f"at {multiplier:.2f}× to win share"
                ),
            ))
        elif self.persona == CompetitorPersona.COOPERATIVE:
            # Don't undercut — actually raise own price slightly to
            # avoid cannibalizing the hero. Reward them later via
            # cooperation_index.
            out.append(CompetitorAction(
                kind="PRICE_MOVE",
                target_id=None,
                payload={
                    "category": target.category,
                    "price_multiplier": round(self._rng.uniform(0.95, 1.05), 3),
                    "reason": "stable pricing",
                },
                body=f"{self.store_id}: holding {target.category} pricing stable",
            ))
        elif self.persona == CompetitorPersona.RECIPROCAL:
            # Mirror what the hero did most recently
            recent = self._hero_action_history[-3:]
            if recent and recent.count("PRICE_DROP") >= 2:
                multiplier = self._rng.uniform(0.65, 0.85)
            else:
                multiplier = self._rng.uniform(0.92, 1.05)
            out.append(CompetitorAction(
                kind="PRICE_MOVE",
                target_id=target.batch_id,
                payload={
                    "category": target.category,
                    "price_multiplier": round(multiplier, 3),
                    "reason": "reciprocal mirror",
                },
                body=f"{self.store_id}: mirroring hero recent moves",
            ))
        return out

    def _farmer_bid_actions(
        self,
        offers: list[SimulatedFarmerOffer],
        current_tick: int,
    ) -> list[CompetitorAction]:
        out: list[CompetitorAction] = []
        if not offers:
            return out

        if self.persona == CompetitorPersona.AGGRESSIVE:
            # Pick any pending offer with reasonable margin and snap it
            for off in offers:
                if not off.is_pending:
                    continue
                # Probability of bidding scales with persona
                if self._rng.random() < 0.55:
                    out.append(CompetitorAction(
                        kind="OFFER_BID",
                        target_id=off.offer_id,
                        payload={
                            "decision": "ACCEPT",
                            "rationale": "fast-bid to deny hero supply",
                        },
                        body=(
                            f"{self.store_id}: accepting {off.offer_id} "
                            f"({off.product_name} {off.quantity_kg}kg)"
                        ),
                    ))
                    break
        elif self.persona == CompetitorPersona.COOPERATIVE:
            if offers and self._rng.random() < 0.20:
                # Politely forward the offer to the hero
                off = offers[0]
                out.append(CompetitorAction(
                    kind="MESSAGE",
                    target_id=off.offer_id,
                    payload={
                        "receiver_id": "store_001",
                        "intent": "FORWARD_OFFER",
                    },
                    body=(
                        f"heads up: {off.farmer_name}'s {off.product_name} "
                        f"offer looks viable for you, we're staying out"
                    ),
                ))
        elif self.persona == CompetitorPersona.RECIPROCAL:
            recent = self._hero_action_history[-4:]
            if recent.count("ACCEPT_OFFER") >= 2 and offers:
                off = offers[0]
                out.append(CompetitorAction(
                    kind="OFFER_BID",
                    target_id=off.offer_id,
                    payload={
                        "decision": "ACCEPT",
                        "rationale": "matching hero acceptance pattern",
                    },
                    body=f"{self.store_id}: accepting {off.offer_id}",
                ))
        return out

    def _trend_grab_actions(
        self,
        categories: list[str],
        current_tick: int,
    ) -> list[CompetitorAction]:
        out: list[CompetitorAction] = []
        if self.persona != CompetitorPersona.AGGRESSIVE:
            return out
        if not categories:
            return out
        cat = self._rng.choice(categories)
        if self._rng.random() < 0.40:
            out.append(CompetitorAction(
                kind="TREND_GRAB",
                target_id=cat,
                payload={"order_quantity_kg": round(self._rng.uniform(8, 22), 1)},
                body=f"{self.store_id}: locking trend supply for {cat}",
            ))
        return out

    def _message_actions(self, current_tick: int) -> list[CompetitorAction]:
        out: list[CompetitorAction] = []
        if self.persona == CompetitorPersona.COOPERATIVE and self._rng.random() < 0.20:
            out.append(CompetitorAction(
                kind="MESSAGE",
                target_id=None,
                payload={"receiver_id": "store_001", "intent": "REVEAL_SURPLUS"},
                body="heads up — we are over-stocked on dairy this week",
            ))
        return out


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _action_to_verb(a: CompetitorAction) -> MessageVerb:
    if a.kind == "OFFER_BID":
        return MessageVerb.BID
    if a.kind == "TREND_GRAB":
        return MessageVerb.COMMIT
    if a.kind == "MESSAGE":
        intent = a.payload.get("intent", "")
        if intent == "FORWARD_OFFER":
            return MessageVerb.REVEAL
        if intent == "REVEAL_SURPLUS":
            return MessageVerb.REVEAL
        return MessageVerb.CHAT
    return MessageVerb.CHAT
